### ISSUE TITLE
File format for data base

### ISSUE THREAD

**Issue by nickhaf** [beckerbenj/eatRecode#10]
Do we want to keep the example data as .xlsx, or maybe use .csv?
Would propably be worth discussing regarding the actual data base. I think I'd prefer .csv though (more universal, no extra dependencies to work with it within the package). Is there a particular reason to choose .xlsx?

Currently, we don't have a data base within the package, correct? Should we open an issue?

-------------------------------------------------
(Answering to both threads here)

Currently, when `eatRecode` refers to a recode data base, this refers to an `.xlsx` file with one or multiple sheets containing look up tables. This is, for instance, implemented in the `createRecodeDB()` and the `getRecodeDB()` functions (which directly read or write `.xlsx` files).

We made the decision in favor of `.xlsx` when creating the package, but discussed alternatives as well (mainly `.csv` or "proper" data base formats such as `SQLite`). Downsides to .csv from my perspective are:
- difficult to inspect and modify with Excel/without R
- issues with German vs English standards
- each look up table is by definition a single file; look up tables can not be as conveniently stored in a single file (without extending the columns), therefore the term data base seems even more misleading to me than in the `.xlsx` case

However, there are certainly advantages of .csv and other alternatives as well (as you mentioned). It would definetely be possible to rewrite/restructure the package in favor of an alternative data format and I think when agreeing on .xlsx we explicitly decided to re-evaluate this later on.

Regardless, in my opinion this is a separate discussion from this issue/PR. The current PR adds an example data base (the title of the PR may be misleading) with two look up tables to the package (in the existing framework). Discussions on alternative file formats should potentially be done together with @enkeflor and @liebelta in a separate issue.

_Originally posted by @beckerbenj in https://github.com/beckerbenj/eatRecode/pull/8#discussion_r1390932547_

**Comment by beckerbenj** [comment]
Discussion with @enkeflor and @liebelta:
File format will be `.csv`, with an additional argument for `write.csv()` vs. `write.csv2()`, with the default being `write.csv2()`

**Comment by apelalina** [comment]
@nickhaf How do we want to handle the issue that the **.csv output of createRecodeDB can't contain multiple sheets** (like the .xlsx version of the output), in the **filepath**? 
Currently (#38), a seperate csv file is created for each sheet. For example, the data base `countries <- list( Europe = data.frame(...), Asia = data.frame(...))` will be saved as `countries_Europe.csv` and `countries_Asia.csv` by `createRecodeDB`. For that, "./countries.csv" is passed as the `filePath` argument of `createRecodeDB`.
- Is the required filepath too unintuitive, since no `countries.csv` file is actually created?
- How should `getRecodeDB` handle multiple tables of a data base? Should "./countries.csv" be passed as the value of `filePath`, even though there is no such file?
- How should `getRecodeList` handle multiple tables of a data base? Should the `filePath` be "./countries.csv", with the table specified by `name = "Asia"` (like with xlsx files), or should the filepath to the desired .csv file be fully written out ("./countries_Asia.csv")?

**Comment by nickhaf** [comment]
I think the best option would be to create a new folder containing the multiple `.csv` files? Wouldn't this solve all three questions, because than the user can just provide the name of the folder, and all data base files could be loaded automatically? 
So maybe createRecodeDB could get a new argument like `DBname` which specifies the folder name for the data base?
Please let me know if this makes sense or if you think this might lead to problems I'm not thinking about.
